[deploy]
mode = 'local'
cookie = 'domain'
data_dir = '/opt/copilot'

[login]
provider = 'authhub'

[login.settings]
host = ''
host_inner = 'http://127.0.0.1:11120'
login_api = ''
app_id = 'ZqMwXAjOAV0GhiTghERAahuR'
app_secret = 'g6QliWAQ89aQJ6qHtKiMuqJubxF28Juw7IGF46GRjb9Ap2g0'

[fastapi]
domain = ''

[security]
half_key1 = 'jtbDsFPxCv1cjXCKwzWU'
half_key2 = 'sEEdztCiw2szN4EtmNR6'
half_key3 = 'NXcp2KUqYjezctZDDasc'
jwt_key = 'MF0DXTp0N9Ky9rscrwHz'

[embedding]
type = 'openai'
endpoint = ''
api_key = ''
model = ''

[rag]
rag_service = 'http://127.0.0.1:9988'

[mongodb]
host = '127.0.0.1'
port = 27017
user = 'euler_copilot'
password = 'YqzzpxJtF5tMAMCrHWw6'
database = 'euler_copilot'

[minio]
endpoint = '127.0.0.1:9000'
access_key = 'minioadmin'
secret_key = 'ZVzc6xJr3B7HsEUibVBh'
secure = false

[llm]
endpoint = ''
key = ''
model = ''
max_tokens = 8192
temperature = 0.7

[function_call]
backend = 'function_call'
endpoint = ''
model = ''
api_key = ''
max_tokens = 8192
temperature = 0.7

[check]
enable = false
words_list = ''

[extra]
sql_url = ''
