[deploy]
mode = 'local'
cookie = 'domain'
data_dir = '/opt/copilot'

[login]
provider = 'authhub'

[login.settings]
host = 'http://127.0.0.1:8000'
host_inner = 'http://127.0.0.1:11120'
login_api = 'http://127.0.0.1:8080/api/auth/logon'
app_id = ''
app_secret = ''

[fastapi]
domain = '127.0.0.1'

[security]
half_key1 = ''
half_key2 = ''
half_key3 = ''
jwt_key = ''

[embedding]
type = 'openai'
endpoint = ''
api_key = ''
model = ''

[rag]
rag_service = 'http://127.0.0.1:9988'

[mongodb]
host = '127.0.0.1'
port = 27017
user = 'euler_copilot'
password = 'YqzzpxJtF5tMAMCrHWw6'
database = 'euler_copilot'

[minio]
endpoint = '127.0.0.1:9000'
access_key = 'minioadmin'
secret_key = ''
secure = false

[llm]
endpoint = ''
key = ''
model = ''
max_tokens = 8192
temperature = 0.7

[function_call]
backend = 'function_call'
endpoint = ''
model = ''
api_key = ''
max_tokens = 8192
temperature = 0.7

[check]
enable = false
words_list = ''

[extra]
sql_url = ''
